getStreamImg: bugfix 'variable referenced before assignment'
bug was introduced sometime during or before 79fd704f59d2befc85303190c2a21a3ce85fb128

Error:
  File "C:\workspace_physical\appengine\bilderapp\bilder.py", line 281, in getStreamImg
    range = len(imgList)
UnboundLocalError: local variable 'imgList' referenced before assignment